name: Process Figma Tokens PR
on: [push]

jobs:
  build:
    name: Process Figma Tokens
    runs-on: ubuntu-latest
    timeout-minutes: 5
  
    steps:
    # checkout to the head of this PR
      - uses: actions/checkout@master
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Dependencies
        run: npm install

      - name: Run token-transformer
        run: npx token-transformer sd-input/src/figma-tokens-output.json sd-input/src/sd-input.json --expandTypography=true
       
     # Convert tokens according to Style Dictionary config
      - run: npx style-dictionary build --config sdConfig.json

     # Add files that were created during a run, e.g. created files from style dictionary or token-transformer.
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Tokens
